junit properties

diff --git a/.github/workflows/junit.yml b/.github/workflows/junit.yml
--- a/.github/workflows/junit.yml
+++ b/.github/workflows/junit.yml
@@ -31,14 +31,26 @@ jobs:
 
       - name: Check coverage thresholds
         run: |
-          COVERAGE=$(sed -n 's/.*<counter.*type="LINE".*covered="\([0-9]*\)".*missed="\([0-9]*\)".*/\1/gp' target/site/jacoco/jacoco.xml)
-          TOTAL_LINES=$(sed -n 's/.*<counter.*type="LINE".*covered="\([0-9]*\)".*missed="\([0-9]*\)".*/\2/gp' target/site/jacoco/jacoco.xml)
-          COVERAGE_PERCENT=$(echo "scale=2; $COVERAGE * 100 / ($COVERAGE + $TOTAL_LINES)" | bc -l)
-          THRESHOLD=80
-          
-          if (( $(echo "$COVERAGE_PERCENT < $THRESHOLD" | bc -l) )); then
-            echo "Error: coverage is below the threshold ($THRESHOLD%)"
+              # Extrair o número de linhas cobertas e não cobertas do relatório JaCoCo
+            COVERAGE=$(sed -n 's/.*<counter type="LINE" covered="\([0-9]*\)".*missed="\([0-9]*\)".*/\1/p' target/site/jacoco/jacoco.xml)
+            TOTAL_LINES=$(sed -n 's/.*<counter type="LINE" covered="\([0-9]*\)".*missed="\([0-9]*\)".*/\2/p' target/site/jacoco/jacoco.xml)
+            
+            # Verificar se COVERAGE e TOTAL_LINES são números válidos
+            if [[ ! $COVERAGE =~ ^[0-9]+$ || ! $TOTAL_LINES =~ ^[0-9]+$ ]]; then
+          echo "Error: Failed to parse coverage numbers from JaCoCo report."
             exit 1
-          else
+            fi
+            
+            # Calcular a porcentagem de cobertura
+            COVERAGE_PERCENT=$(( $COVERAGE * 100 / ($COVERAGE + $TOTAL_LINES) ))
+            
+            # Definir o limiar de cobertura desejado (80% neste exemplo)
+            THRESHOLD=80
+            
+            # Comparar a cobertura percentual com o limiar
+            if (( $COVERAGE_PERCENT < $THRESHOLD )); then
+          echo "Error: coverage is below the threshold ($THRESHOLD%)"
+            exit 1
+            else
             echo "Coverage is satisfactory"
-          fi
+            fi
